#!/bin/bash
# Script pour afficher les étapes d'ajout du port 5506 à Google Cloud Console

echo "=========================================="
echo "🔧 AJOUT DU PORT 5506 À GOOGLE CLOUD"
echo "=========================================="
echo ""
echo "Vous accédez depuis: http://127.0.0.1:5506"
echo ""
echo "ÉTAPES POUR CORRIGER:"
echo ""
echo "1️⃣  Ouvrir Google Cloud Console:"
echo "    👉 https://console.cloud.google.com/apis/credentials"
echo ""
echo "2️⃣  Sélectionner le projet 'Prestige Shop Express New'"
echo ""
echo "3️⃣  Cliquer sur l'ID client OAuth:"
echo "    722931671687-fj2ph80jpqvlqmqnmc3aepdfqtsl7eqe.apps.googleusercontent.com"
echo ""
echo "4️⃣  Scroll à 'Origines JavaScript autorisées'"
echo ""
echo "5️⃣  Cliquer '+ Ajouter URI' ou '+ ADD URI'"
echo ""
echo "6️⃣  Ajouter CHACUNE de ces deux origines:"
echo "    • http://localhost:5506"
echo "    • http://127.0.0.1:5506"
echo ""
echo "7️⃣  Cliquer 'Enregistrer' ou 'Save'"
echo ""
echo "8️⃣  ATTENDRE 3-5 MINUTES que les changements se propagent"
echo ""
echo "9️⃣  Vider le cache du navigateur:"
echo "    • Windows: Ctrl+Shift+Delete"
echo "    • Mac: Cmd+Shift+Delete"
echo ""
echo "🔟 Rechargez la page:"
echo "    • Windows: Ctrl+F5"
echo "    • Mac: Cmd+Shift+R"
echo ""
echo "=========================================="
echo "✅ Testez maintenant la connexion Google!"
echo "=========================================="
